#!/bin/bash

ALL_NAMESPACES=($(kubectl get ns --no-headers | awk '{print $1}'))

show_menu() {
	local n=1
	for ns in ${ALL_NAMESPACES[@]}; do
		echo "$n. $ns"
		(( n += 1 ))
	done
}

read_options(){
	local choice
	read -p "Choose a namespace [1 - ${#ALL_NAMESPACES[@]}] " choice
	kubectl config set-context $(kubectl config current-context) --namespace=${ALL_NAMESPACES[ (( choice - 1 )) ]}
}

show_menu
read_options
