#!/bin/bash
# This shows a list of namespaces and updates context to switch between them
# Should be expanded to highlight current namespace and have other use options
# For example simply list current namespace

# Set current context
CURRENT_CONTEXT=$(kubectl config current-context)
# Get namespaces
ALL_NAMESPACES=($(kubectl get ns --no-headers | awk '{print $1}'))

# Create a menu for namespaces
# TODO: remove non-user namespaces (kube-system, default etc)
show_menu() {
  local n=1
  for ns in ${ALL_NAMESPACES[@]}; do
    echo "$n. $ns"
    (( n += 1 ))
  done
}

read_options(){
  local choice
  read -p "Choose a namespace [1 - ${#ALL_NAMESPACES[@]}] " choice
  kubectl config set-context ${CURRENT_CONTEXT} --namespace=${ALL_NAMESPACES[ (( choice - 1 )) ]} > /dev/null 2>&1
  echo "Switched to Namespace: ${ALL_NAMESPACES[ (( choice - 1 )) ]}"
}

show_menu
read_options
